### ISSUE TITLE
Make "sex" a drop down in spreadsheet

### ISSUE THREAD

**Issue by jczech** [brain-image-library/bil_site#30]

**Comment by SeanDeitrich** [comment]
The spreadsheet changes will need to be done on a windows computer. I tried making the changes in LibreOffice and it wouldn't save them because of formatting issues. I don't think this will be a problem with Excel. 

That being said I'll do this and the other spreadsheet issues from home today. Should only take me 10m.

**Comment by jczech** [comment]
This works in the ods file. We just need to do it for the xls file now.

**Comment by jczech** [comment]
This work in the excel spreadsheet now too.
